module.exports =
  [ 'type'
  , 'shortTitle'
  , 'longTitle'
  , 'subTitle'
  , 'crops'
  , '__fullUrlPath'
  , '__liteSection'
  , 'displayDate'
  , 'showDisplayDate'
  , 'tags'
  , 'images'
  , 'downloads'
  , 'commentCount'
  , 'viewCount'
  , 'standfirst'
  ]
